### ISSUE TITLE
文档说明

### ISSUE THREAD

**Issue by cnxy** [Zongsoft/Zongsoft.CoreLibrary#4]
请问能不能写个文档说明？？？

**Comment by PopeyeZhong** [comment]
@cnxy 非常抱歉，之前没有推广的打算也没有写过文档，但是，从现在开始，正在疯狂补写文档。还请稍等一段时间。。。 有最新进展我会在公众号发消息的。

**Comment by cnxy** [comment]
微信公众号是？

**Comment by PopeyeZhong** [comment]
搜索下： Zongsoft
或者扫码： ![Zongsoft微信公众号](https://zongsoft.github.io/blog/assets/zongsoft-wechat-qrcode.jpg)

你可以看下我们的官网： [https://zongsoft.github.io/blog](https://zongsoft.github.io/blog/)
